<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2b26fe99-f8ce-40a0-a978-18fe55b35c36</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrigdeService.Application\BrigdeService.Application.csproj" />
    <ProjectReference Include="..\BrigdeService.Infrastructure\BrigdeService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
