<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>045622a2-7b9a-4ec1-87ad-33aa38565afd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IngestService.Application\IngestService.Application.csproj" />
    <ProjectReference Include="..\IngestService.Infrastructure\IngestService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
